[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  # Ensure pnpm is used by Netlify's build image
  PNPM_VERSION = "8" # Specify a version or let Netlify use its default

# Redirects rule for Single Page Applications (SPA)
# This ensures that all paths are served by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# It's good practice to define environment variables in Netlify's UI,
# but if you need to pass them during build time and they are not sensitive,
# you can use this section. For sensitive keys, use Netlify's UI.
# For this project, the .env file should be automatically picked up by Vite during the build.
# However, Netlify's build environment might not automatically source .env files in the same way a local dev server does.
# To ensure Vite has access to these, we can explicitly list them here if needed,
# but a better practice for Netlify is to set them in the Netlify UI.
# For now, we assume Vite's `import.meta.env` will work as expected with .env file during Netlify build.
# If not, we might need to adjust by using Netlify build environment variables that get passed to the vite build.

[dev]
  command = "pnpm run dev" # Command to run the dev server
  port = 5173 # Default Vite port, can be adjusted
  publish = "dist" # Directory to serve locally
